#!/usr/bin/env Rscript
# =============================================================================
# plot_susiex_pip.R
#
# Purpose: Visualizes cross-ancestry fine-mapping results generated by SuSiEx.
#
# This script reads the SuSiEx `.snp` and `.cs` output files to generate a 
# publication-ready scatter plot of Posterior Inclusion Probabilities (PIP) 
# across a genomic region. 
#
# ── Plotting Logic ────────────────────────────────────────────────────────────
#
#   1. Background (Noise): Plots all variants evaluated in the region using
#      the `.snp` file, summing individual PIP(CS) columns to determine the
#      overall background probability.
#   2. Credible Sets (Signal): Overlays variants formally assigned to a 
#      Credible Set (CS) using the `.cs` file, coloring them by CS_ID and 
#      adding a distinct border (shape 21).
#   3. Labeling: Dynamically identifies the variant with the highest PIP in 
#      each Credible Set and labels it using ggrepel to prevent text overlap.
#
# ── Usage ─────────────────────────────────────────────────────────────────────
#
#   Rscript plot_susiex_pip.R \
#       --snp       /data/h_vmac/zhanm32/susiex/data/test/SPAREAD_EUR_SuSiEx.output.cs95.snp \
#       --cs        /data/h_vmac/zhanm32/susiex/data/test/SPAREAD_EUR_SuSiEx.output.cs95.cs \
#       --outdir    /data/h_vmac/zhanm32/susiex/data/test \
#       --outprefix SPAREAD_EUR_SuSiEx.output.cs95
#
# ── Arguments ─────────────────────────────────────────────────────────────────
#
#   --snp        Path to the SuSiEx .snp file          [required]
#   --cs         Path to the SuSiEx .cs file           [required]
#   --outdir     Directory to save the plots           [default: ./]
#   --outprefix  Prefix name for output image files    [default: SuSiEx_Plot]
#
# ── Output files ──────────────────────────────────────────────────────────────
#
#   <outdir>/<outprefix>_PIP.pdf    (Vector format for publication)
#   <outdir>/<outprefix>_PIP.png    (300 DPI raster for quick viewing)
#
# ── R packages required ───────────────────────────────────────────────────────
#
#   optparse, dplyr, readr, ggplot2, ggrepel
#
# =============================================================================

# Enforce shared ACCRE R library path
.libPaths(c("/data/h_vmac/waltes2/Coloc/Conda_Environment_New/rlib-4.5.0", .libPaths()))

suppressPackageStartupMessages({
  library(optparse)
  library(dplyr)
  library(ggplot2)
  library(readr)
  library(ggrepel)
})

# =============================================================================
# CLI arguments
# =============================================================================
option_list <- list(
  make_option(c("--snp"), type="character", default=NULL, 
              help="Path to the SuSiEx .snp file (e.g., SPAREAD_EUR_SuSiEx.output.cs95.snp)"),
  make_option(c("--cs"), type="character", default=NULL, 
              help="Path to the SuSiEx .cs file (e.g., SPAREAD_EUR_SuSiEx.output.cs95.cs)"),
  make_option(c("--outdir"), type="character", default="./", 
              help="Directory to save the plots [default: current directory]"),
  make_option(c("--outprefix"), type="character", default="SuSiEx_Plot", 
              help="Prefix name for the output image files [default: SuSiEx_Plot]")
)

opt <- parse_args(OptionParser(option_list=option_list))

# Ensure required arguments are provided
if (is.null(opt$snp) || is.null(opt$cs)) {
  cat("\n[ERROR] Both --snp and --cs file paths must be provided.\n")
  cat("        Run with --help for usage instructions.\n\n")
  quit(status = 1)
}

# Ensure output directory exists
if (!dir.exists(opt$outdir)) {
  dir.create(opt$outdir, recursive = TRUE, showWarnings = FALSE)
}

cat("============================================================\n")
cat(" plot_susiex_pip.R\n")
cat("============================================================\n")
cat(sprintf(" SNP file   : %s\n", opt$snp))
cat(sprintf(" CS file    : %s\n", opt$cs))
cat(sprintf(" Out Dir    : %s\n", opt$outdir))
cat(sprintf(" Out Prefix : %s\n", opt$outprefix))
cat("============================================================\n\n")

# =============================================================================
# Data Loading & Processing
# =============================================================================
cat("[1/3] Reading SuSiEx output files...\n")
df_snp <- read_tsv(opt$snp, show_col_types = FALSE)
df_cs  <- read_tsv(opt$cs, show_col_types = FALSE)

cat("[2/3] Calculating Overall PIP and identifying top variants...\n")
# The .snp file contains individual columns for each CS, e.g., PIP(CS1).
# We sum them to get the overall probability for the background plot.
pip_cols <- grep("^PIP\\(CS", names(df_snp), value = TRUE)
if (length(pip_cols) > 0) {
  df_snp$Overall_PIP <- rowSums(df_snp[pip_cols], na.rm = TRUE)
} else {
  cat("[ERROR] Could not find PIP(CS...) columns in the .snp file.\n")
  quit(status = 1)
}

# Identify the Top SNP(s) for labeling
top_snps <- df_cs %>%
  group_by(CS_ID) %>%
  slice_max(order_by = CS_PIP, n = 1, with_ties = FALSE) %>%
  ungroup()

n_cs <- nrow(top_snps)
cat(sprintf("      Found %d Credible Set(s) to plot.\n", n_cs))

# =============================================================================
# Generating Plot
# =============================================================================
cat("[3/3] Generating visualization...\n")

p <- ggplot() +
  # Background SNPs (grey dots)
  geom_point(data = df_snp, 
             aes(x = BP, y = Overall_PIP), 
             color = "grey70", size = 1.5, alpha = 0.6) +
  
  # Highlight the CS SNPs (colored circles with black borders)
  geom_point(data = df_cs, 
             aes(x = BP, y = OVRL_PIP, fill = as.factor(CS_ID)),
             shape = 21, color = "black", size = 3, stroke = 0.8) +
  
  # Label the maximum PIP SNPs
  geom_text_repel(data = top_snps, 
                  aes(x = BP, y = OVRL_PIP, label = SNP),
                  nudge_y = 0.08, 
                  box.padding = 0.5,
                  point.padding = 0.3,
                  fontface = "bold",
                  color = "black",
                  segment.color = "grey50") +
  
  # Formatting and Aesthetics
  scale_fill_brewer(palette = "Set1", name = "Credible Set") +
  theme_bw(base_size = 14) +
  labs(title = paste("SuSiEx Fine-Mapping PIP:", opt$outprefix),
       x = "Base Pair Position (BP)",
       y = "Posterior Inclusion Probability (PIP)") +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    legend.position = "bottom"
  )

# =============================================================================
# Save Outputs
# =============================================================================
out_pdf <- file.path(opt$outdir, paste0(opt$outprefix, "_PIP.pdf"))
out_png <- file.path(opt$outdir, paste0(opt$outprefix, "_PIP.png"))

ggsave(out_pdf, p, width = 10, height = 6)
ggsave(out_png, p, width = 10, height = 6, dpi = 300)

cat("\n============================================================\n")
cat(" Done!\n")
cat("============================================================\n")
cat(sprintf(" PDF saved to : %s\n", out_pdf))
cat(sprintf(" PNG saved to : %s\n", out_png))